### ISSUE TITLE
Binary Support

### ISSUE THREAD

**Issue by dytsai** [Automattic/socket.io-redis#33]
Since 1.0, socket.io starts to support binary data by encoding object like below

[ '52-17{"a":{"_placeholder":true,"num":0},"b":5,"c":{"_placeholder":true,"num":1}}', <Buffer 41 42 43>,  <Buffer 44 45 46> ]

The idea is to extract the binary part out and put a placehoder in the JSON as metadata. However, after encoding (in this call: Adapter.prototype.broadcast.call(this, packet, opts);), the original packet is changed as well. The original packet doesn't have any binary part either so only the JSON with placehoder gets published to redis server.

Maybe changing the order of these two lines can work. Publish the packet before its binary part got taken away.

118   Adapter.prototype.broadcast.call(this, packet, opts);
119   if (!remote) pub.publish(key, msgpack.encode([packet, opts]));

**Comment by rauchg** [comment]
We have binary support
