### ISSUE TITLE
Problem using UNIX domain socket

### ISSUE THREAD

**Issue by swmoon203** [Automattic/socket.io-redis#43]
it fails on decoding message
```
var args = msgpack.decode(msg);
```

> events.js:72
        throw er; // Unhandled 'error' event
              ^
SyntaxError: Unexpected token �
    at Object.parse (native)

**Comment by rauchg** [comment]
I removed the `socket` option, it made no sense

**Comment by goalsoft** [comment]
How would not make sense? Unix socket with faster

**Comment by rauchg** [comment]
Because in any case it should be two sockets, considering we need to open connections to Redis.
