### ISSUE TITLE
Documentation doesn't match release

### ISSUE THREAD

**Issue by buunguyen** [Automattic/socket.io-redis#54]
From the readme, I can handle Redis connection error as follows:
```javascript
adapter.pubClient.on('error', function(){});
adapter.subClient.on('error', function(){});
```

But I couldn't do it at all. Turns out the latest release version (0.1.4) doesn't implement that. Can you release a version that matches the documentation? If not, I think the documentation should be updated or at least made clear to avoid people from pulling their hair. Thanks!

**Comment by ZloyDyadka** [comment]
+

**Comment by lmf** [comment]
+1

**Comment by rauchg** [comment]
Actually, it didn't match `master` either. I just fixed that.
