### ISSUE TITLE
Sending a message from one node to a specific socket on another node.

### ISSUE THREAD

**Issue by allthetime** [Automattic/socket.io-redis#56]
So I'm trying to run a multi-node system where one user can initiate private contact with another user, potentially across nodes, but I'm not sure how to do this with a multi-node system and socket.io-redis. 

Originally with a single node, I was simply attaching session objects to each socket. This allowed me to search for socketIds based on session ids and then send a message accordingly, something like: client1 -> socket-server -> client 2.

But now, I can't search the sockets of one node from another. 

I'm assuming there must be a way to collect all the sockets connected to the entire network from the redis cache used by socket.io, but I'm not sure and I don't know how to find out. I've been inspecting redis with a desktop client and I can't see anything being cached by socket-io.

Anyways, is it possible to scan the sockets of one node from another node? Or, is what I'm trying to do even possible in this framework?

**Comment by allthetime** [comment]
Nevermind just had to keep track of socketIds in relation to sessions in redis

**Comment by baranx** [comment]
Hi,

Currently I'm struggling with the same issue. I'm new to socket.io and redis. Could you please explain me how did you solve this?

Thanks in advance...
